// Role-based access control helpers.
// Roles: ADMIN, TEAM_LEAD, DEVELOPER

export const ACTIONS = {
  // Workspace / org
  MANAGE_WORKSPACE: "MANAGE_WORKSPACE",
  CREATE_WORKSPACE: "CREATE_WORKSPACE",
  INVITE_MEMBERS: "INVITE_MEMBERS",
  ASSIGN_ROLES: "ASSIGN_ROLES",
  VIEW_ORG_ANALYTICS: "VIEW_ORG_ANALYTICS",
  ACCESS_SETTINGS: "ACCESS_SETTINGS",

  // Projects
  CREATE_PROJECT: "CREATE_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",
  ASSIGN_PROJECT: "ASSIGN_PROJECT",
  MANAGE_PROJECT: "MANAGE_PROJECT",

  // Sprints
  MANAGE_SPRINT: "MANAGE_SPRINT",

  // Tasks
  CREATE_TASK: "CREATE_TASK",
  DELETE_TASK: "DELETE_TASK",
  ASSIGN_TASK: "ASSIGN_TASK",
  MOVE_TASK_ANY: "MOVE_TASK_ANY",     // arbitrary status changes (lead/admin)
  UPDATE_OWN_TASK: "UPDATE_OWN_TASK", // dev can update progress on their own
  SUBMIT_FOR_REVIEW: "SUBMIT_FOR_REVIEW",
  APPROVE_TASK: "APPROVE_TASK",
  REJECT_TASK: "REJECT_TASK",
  COMMENT: "COMMENT",
};

const MATRIX = {
  ADMIN: new Set([
    "MANAGE_WORKSPACE","CREATE_WORKSPACE","INVITE_MEMBERS","ASSIGN_ROLES",
    "VIEW_ORG_ANALYTICS","ACCESS_SETTINGS",
    "CREATE_PROJECT","DELETE_PROJECT","ASSIGN_PROJECT","MANAGE_PROJECT",
    "MANAGE_SPRINT",
    "CREATE_TASK","DELETE_TASK","ASSIGN_TASK","MOVE_TASK_ANY","UPDATE_OWN_TASK",
    "SUBMIT_FOR_REVIEW","APPROVE_TASK","REJECT_TASK","COMMENT",
  ]),
  TEAM_LEAD: new Set([
    "INVITE_MEMBERS","ACCESS_SETTINGS",
    "MANAGE_PROJECT","ASSIGN_PROJECT","MANAGE_SPRINT",
    "CREATE_TASK","DELETE_TASK","ASSIGN_TASK","MOVE_TASK_ANY","UPDATE_OWN_TASK",
    "SUBMIT_FOR_REVIEW","APPROVE_TASK","REJECT_TASK","COMMENT",
  ]),
  DEVELOPER: new Set([
    "ACCESS_SETTINGS",
    "UPDATE_OWN_TASK","SUBMIT_FOR_REVIEW","COMMENT",
  ]),
};

export function can(role, action) {
  if (!role) return false;
  return MATRIX[role]?.has(action) ?? false;
}

export function canAny(role, actions) {
  return actions.some((a) => can(role, a));
}
